### ISSUE TITLE
ODHack: Document the Registry contract

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/tokenbound-contract-docs#1]
Description: 
This documentation will serve as a reference for developers and users who want to understand the functionality of the Registry contract.

**Goals:**

- Explain the purpose of the Registry contract.
- Document the available functions.
**References:**

- Link to existing documentation: https://docs.tbaexplorer.com/starknet-tokenbound-sdk/introduction-to-tokenbound
- Link to the Registry contract code: https://github.com/horuslabsio/TBA/blob/v3/src/registry/registry.cairo
- New to contract documentations? Check out this sample docs as a guide: https://contracts-v2-docs.lens.xyz/contracts/libraries/ProfileLib.sol/library.ProfileLib

**Comment by od-hunter** [comment]
Hi @Darlington02 , please can I be assigned this please? 

I'm also good at documentations. Below are some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308#event-13866062226

https://github.com/keep-starknet-strange/joyboy/pull/143#event-13034455918,

https://github.com/horuslabsio/Starknet-Scaffold/pull/94#event-13007360671.

Some of my documentations outside GitHub:

https://t.co/ZgK0ccPZpw,

https://t.co/GnBqVQPECz.

Please I’m ready to work, assign me please.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/erc6551-token-bound-accounts-on-starknet).

### My background and how it can be leveraged
i am a frontend developer with experience in frontend development and also technical writing
below are some of my previous articles:


- [cairo book](https://github.com/cairo-book/cairo-book/pull/982)
- [what happens when you press enter key](https://hackmd.io/@nuelo/whathappenswhen)
- [cairo smart contract](https://hackmd.io/@nuelo/rJroBcwzC)

### How I plan on tackling this issue
I will start by thoroughly reviewing the Registry contract code available at this link. This will help me understand its functionality, structure, and the purpose of each function within the contract.

I will articulate the main objectives of the Registry contract. This includes its role in managing and storing data related to token-bound accounts, how it interacts with other components, and its importance in the broader application context.

I will create a comprehensive section that lists and explains each function available in the Registry contract. For each function, I will include:
The function name.
A brief description of what the function does.
The parameters it accepts and their types.
The return values and their types, if applicable.
Any potential side effects or important notes related to the function's usage.

And include possible reference
